### ISSUE TITLE
Undocumented rate limit gives 503 instead of 429

### ISSUE THREAD

**Issue by felix920506** [JPVenson/Jellyfin.HardwareVisualizer#8]
When obtaining tests from the server, a 503 error is returned instead of 429 when rate limited. This rate limit is undocumented in the swagger Ui docs.

**Comment by JPVenson** [comment]
fixed as changed to 429

**Comment by BotBlake** [comment]
Is this Change documented in the Whitepaper?

**Comment by JPVenson** [comment]
rate limites are not documented at all in the whitepaper for security reasons as well as its a moving target.
What i will later maybe add is that the client always has to respect a 429 with the retry-after header but thats good http client behavior anyway
https://www.rfc-editor.org/rfc/rfc6585#section-4

**Comment by BotBlake** [comment]
Perfect 👌
That was exactly was I meant.
